backbone: "CLIP-ViT-L/14"
resolution: 224

output_dir: null
print_freq: 10

seed: 0
deterministic: True
num_workers: 8
prec: "amp"

num_epochs: 10
# base: bs16 for lr0.01, based on linear learning rate
batch_size: 64
accum_step: 1
# lr: 0.01
lr: 0.02
weight_decay: 5e-4
momentum: 0.9
loss_type: "LA"
classifier: "CosineClassifier"

init_head: "text_feat"
tte: False
expand: 21
