backbone: "CLIP-RN101"
resolution: 224

output_dir: null
print_freq: 10

seed: 0
deterministic: True
num_workers: 8
prec: "amp"

num_epochs: 10
batch_size: 128
accum_step: 1
lr: 0.01
weight_decay: 5e-4
momentum: 0.9
loss_type: "LA"
classifier: "CosineClassifier"

bias_tuning: False
bn_tuning: False
ssf_attn: False

init_head: "text_feat"
tte: False
expand: 24
