# This equals to original in21k_vit_b16_g4.yaml
backbone: "IN21K-ViT-B/16"
resolution: 224

output_dir: null
print_freq: 10

seed: 0
deterministic: True
num_workers: 8
prec: "amp"

num_epochs: 10
# base: bs128 for lr0.01, based on sqrt scaling rule
batch_size: 128
accum_step: 1
lr: 0.01
weight_decay: 5e-4
momentum: 0.9
loss_type: "LA"
classifier: "CosineClassifier"

init_head: "class_mean"
tte: False
expand: 24