# g4f means large batch size on 4 GPUs
backbone: "SatMAE-ViT-L/16"
resolution: 224

output_dir: null
print_freq: 10

seed: 0
deterministic: True
num_workers: 8
prec: "amp"

num_epochs: 10
# base: bs128 for lr0.01, based on sqrt scaling rule
batch_size: 32
accum_step: 1
lr: 0.005
weight_decay: 5e-4
momentum: 0.9
loss_type: "LA"
classifier: "CosineClassifier"

init_head: "class_mean"
tte: False
expand: 24

zero_shot: false
test_only: false
test_train: false